// src/products.js
export const products = [
  {
    id: 1,
    name: "waffle with Berries",
    price: 10.99,
    category: "waffle",
    image: "image-waffle-tablet.jpg",
    quantity: 1,
    icon:"icon-remove-item.svg"
  },
  {
    id: 2,
    name: "Vanilla Bean Crème Brûlée",
    price: 4.33,
    category: "Creme Brulee",
    image: "image-creme-brulee-tablet.jpg",
    quantity: 1,
  },
  {
    id: 3,
    name: "Macaron Mix of Five",
    price: 5.09,
    category: "Macaron",
    image: "image-macaron-desktop.jpg",
    quantity: 1,
  },
  {
    id: 4,
    name: "Classic Tiramisu",
    price: 5.99,
    category: "Tiramisu",
    image: "image-tiramisu-desktop.jpg",
    quantity: 1,
  },
  {
    id: 5,
    name: "istachio Baklavae",
    price: 6.29,
    category: "Baklava",
    image: "image-baklava-desktop.jpg",
    quantity: 1,
  },
  {
    id: 6,
    name: "Lemon Meringue Pie",
    price: 5.19,
    category: "Pie",
    image: "image-meringue-desktop.jpg",
    quantity: 1,
  },
  {
    id: 7,
    name: "Red Velvet Cake",
    price: 5.19,
    category: "Cake",
    image: "image-cake-mobile.jpg",
    quantity: 1,
  },
  {
    id: 8,
    name: "Salted Caramel Brownie",
    price: 4.99,
    category: "Brownie",
    image: "image-brownie-tablet.jpg",
    quantity: 1,
  },
  {
    id: 9,
    name: "Vanilla Panna Cotta",
    price: 6.59,
    category: "Panna Cotta",
    image: "image-panna-cotta-tablet.jpg",
    quantity: 1,
  },
];
